# PostgreSQL Local con Docker para Sistema de Rifas
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rifas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sistema_rifas
      POSTGRES_USER: rifas_user
      POSTGRES_PASSWORD: rifas_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - rifas_network

  # PgAdmin para administración (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rifas-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rifas.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rifas_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  rifas_network:
    driver: bridge
